// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'it'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	route_1: NamespaceRoute1Translation
}

type RootTranslation = {
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​S​v​e​l​t​e​ ​F​a​l​l​ ​S​u​m​m​i​t​ ​{​y​e​a​r​}
	 * @param {number} year
	 */
	HI: RequiredParams<'year'>
	/**
	 * {​0​}​ ​l​i​v​e​ ​s​p​e​c​t​a​t​o​r​{​{​s​}​}
	 * @param {string | number | boolean} 0
	 */
	spectators: RequiredParams<'0'>
	summit: {
		/**
		 * {​0​|​s​i​m​p​l​e​D​a​t​e​}
		 * @param {Date} 0
		 */
		schedule: RequiredParams<'0|simpleDate'>
	}
}

export type NamespaceRoute1Translation = {
	/**
	 * w​e​l​c​o​m​e​ ​t​o​ ​r​o​u​t​e​_​1
	 */
	welcome: string
}

export type Namespaces =
	| 'route_1'

type DisallowNamespaces = {
	/**
	 * reserved for 'route_1'-namespace\
	 * you need to use the `./route_1/index.ts` file instead
	 */
	route_1?: "[typesafe-i18n] reserved for 'route_1'-namespace. You need to use the `./route_1/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * Welcome to Svelte Fall Summit {year}
	 */
	HI: (arg: { year: number }) => LocalizedString
	/**
	 * {0} live spectator{{s}}
	 */
	spectators: (arg0: string | number | boolean) => LocalizedString
	summit: {
		/**
		 * {0|simpleDate}
		 */
		schedule: (arg0: Date) => LocalizedString
	}
	route_1: {
		/**
		 * welcome to route_1
		 */
		welcome: () => LocalizedString
	}
}

export type Formatters = {
	simpleDate: (value: Date) => unknown
}
